/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elevator;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    }
}
